import mongoose from "mongoose";
import Student from "../models/studentSchema.js";
import Room from "../models/roomSchema.js";

main().catch((err) => console.log(err));

async function main() {
  await mongoose.connect("mongodb://127.0.0.1:27017/Hostel");
}

const rooms_seed = [
  { block: "E", floor: 1, roomNumber: 1 },
  { block: "E", floor: 1, roomNumber: 2 },
  { block: "E", floor: 1, roomNumber: 3 },
  { block: "E", floor: 1, roomNumber: 4 },
  { block: "E", floor: 1, roomNumber: 5 },
  { block: "E", floor: 1, roomNumber: 6 },
  { block: "E", floor: 1, roomNumber: 7 },
  { block: "E", floor: 1, roomNumber: 8 },
  { block: "E", floor: 1, roomNumber: 9 },
  { block: "E", floor: 2, roomNumber: 1 },
  { block: "E", floor: 2, roomNumber: 2 },
  { block: "E", floor: 2, roomNumber: 3 },
  { block: "E", floor: 2, roomNumber: 4 },
  { block: "E", floor: 2, roomNumber: 5 },
  { block: "E", floor: 2, roomNumber: 6 },
  { block: "E", floor: 2, roomNumber: 7 },
  { block: "E", floor: 2, roomNumber: 8 },
  { block: "E", floor: 2, roomNumber: 9 },
  { block: "E", floor: 3, roomNumber: 1 },
  { block: "E", floor: 3, roomNumber: 2 },
  { block: "E", floor: 3, roomNumber: 3 },
  { block: "E", floor: 3, roomNumber: 4 },
  { block: "E", floor: 3, roomNumber: 5 },
  { block: "E", floor: 3, roomNumber: 6 },
  { block: "E", floor: 3, roomNumber: 7 },
  { block: "E", floor: 3, roomNumber: 8 },
  { block: "E", floor: 3, roomNumber: 9 },

  { block: "F", floor: 1, roomNumber: 1 },
  { block: "F", floor: 1, roomNumber: 2 },
  { block: "F", floor: 1, roomNumber: 3 },
  { block: "F", floor: 1, roomNumber: 4 },
  { block: "F", floor: 1, roomNumber: 5 },
  { block: "F", floor: 1, roomNumber: 6 },
  { block: "F", floor: 1, roomNumber: 7 },
  { block: "F", floor: 2, roomNumber: 1 },
  { block: "F", floor: 2, roomNumber: 2 },
  { block: "F", floor: 2, roomNumber: 3 },
  { block: "F", floor: 2, roomNumber: 4 },
  { block: "F", floor: 2, roomNumber: 5 },
  { block: "F", floor: 2, roomNumber: 6 },
  { block: "F", floor: 2, roomNumber: 7 },
  { block: "F", floor: 3, roomNumber: 1 },
  { block: "F", floor: 3, roomNumber: 2 },
  { block: "F", floor: 3, roomNumber: 3 },
  { block: "F", floor: 3, roomNumber: 4 },
  { block: "F", floor: 3, roomNumber: 5 },
  { block: "F", floor: 3, roomNumber: 6 },
  { block: "F", floor: 3, roomNumber: 7 },

  { block: "G", floor: 1, roomNumber: 1 },
  { block: "G", floor: 1, roomNumber: 2 },
  { block: "G", floor: 1, roomNumber: 3 },
  { block: "G", floor: 1, roomNumber: 4 },
  { block: "G", floor: 1, roomNumber: 5 },
  { block: "G", floor: 1, roomNumber: 6 },
  { block: "G", floor: 1, roomNumber: 7 },
  { block: "G", floor: 1, roomNumber: 8 },
  { block: "G", floor: 1, roomNumber: 9 },
  { block: "G", floor: 2, roomNumber: 1 },
  { block: "G", floor: 2, roomNumber: 2 },
  { block: "G", floor: 2, roomNumber: 3 },
  { block: "G", floor: 2, roomNumber: 4 },
  { block: "G", floor: 2, roomNumber: 5 },
  { block: "G", floor: 2, roomNumber: 6 },
  { block: "G", floor: 2, roomNumber: 7 },
  { block: "G", floor: 2, roomNumber: 8 },
  { block: "G", floor: 2, roomNumber: 9 },
  { block: "G", floor: 3, roomNumber: 1 },
  { block: "G", floor: 3, roomNumber: 2 },
  { block: "G", floor: 3, roomNumber: 3 },
  { block: "G", floor: 3, roomNumber: 4 },
  { block: "G", floor: 3, roomNumber: 5 },
  { block: "G", floor: 3, roomNumber: 6 },
  { block: "G", floor: 3, roomNumber: 7 },
  { block: "G", floor: 3, roomNumber: 8 },
  { block: "G", floor: 3, roomNumber: 9 },

  { block: "I", floor: 1, roomNumber: 1 },
  { block: "I", floor: 1, roomNumber: 2 },
  { block: "I", floor: 1, roomNumber: 3 },
  { block: "I", floor: 1, roomNumber: 4 },
  { block: "I", floor: 1, roomNumber: 5 },
  { block: "I", floor: 1, roomNumber: 6 },
  { block: "I", floor: 1, roomNumber: 7 },
  { block: "I", floor: 1, roomNumber: 8 },
  { block: "I", floor: 1, roomNumber: 9 },
  { block: "I", floor: 1, roomNumber: 10 },
  { block: "I", floor: 1, roomNumber: 11 },
  { block: "I", floor: 1, roomNumber: 12 },
  { block: "I", floor: 1, roomNumber: 13 },
  { block: "I", floor: 1, roomNumber: 14 },
  { block: "I", floor: 1, roomNumber: 15 },
  { block: "I", floor: 1, roomNumber: 16 },
  { block: "I", floor: 1, roomNumber: 17 },
  { block: "I", floor: 1, roomNumber: 18 },
  { block: "I", floor: 1, roomNumber: 19 },
  { block: "I", floor: 1, roomNumber: 20 },
  { block: "I", floor: 2, roomNumber: 1 },
  { block: "I", floor: 2, roomNumber: 2 },
  { block: "I", floor: 2, roomNumber: 3 },
  { block: "I", floor: 2, roomNumber: 4 },
  { block: "I", floor: 2, roomNumber: 5 },
  { block: "I", floor: 2, roomNumber: 6 },
  { block: "I", floor: 2, roomNumber: 7 },
  { block: "I", floor: 2, roomNumber: 8 },
  { block: "I", floor: 2, roomNumber: 9 },
  { block: "I", floor: 2, roomNumber: 10 },
  { block: "I", floor: 2, roomNumber: 11 },
  { block: "I", floor: 2, roomNumber: 12 },
  { block: "I", floor: 2, roomNumber: 13 },
  { block: "I", floor: 2, roomNumber: 14 },
  { block: "I", floor: 2, roomNumber: 15 },
  { block: "I", floor: 2, roomNumber: 16 },
  { block: "I", floor: 2, roomNumber: 17 },
  { block: "I", floor: 2, roomNumber: 18 },
  { block: "I", floor: 2, roomNumber: 19 },
  { block: "I", floor: 2, roomNumber: 20 },
  { block: "I", floor: 3, roomNumber: 1 },
  { block: "I", floor: 3, roomNumber: 2 },
  { block: "I", floor: 3, roomNumber: 3 },
  { block: "I", floor: 3, roomNumber: 4 },
  { block: "I", floor: 3, roomNumber: 5 },
  { block: "I", floor: 3, roomNumber: 6 },
  { block: "I", floor: 3, roomNumber: 7 },
  { block: "I", floor: 3, roomNumber: 8 },
  { block: "I", floor: 3, roomNumber: 9 },
  { block: "I", floor: 3, roomNumber: 10 },
  { block: "I", floor: 3, roomNumber: 11 },
  { block: "I", floor: 3, roomNumber: 12 },
  { block: "I", floor: 3, roomNumber: 13 },
  { block: "I", floor: 3, roomNumber: 14 },
  { block: "I", floor: 3, roomNumber: 15 },
  { block: "I", floor: 3, roomNumber: 16 },
  { block: "I", floor: 3, roomNumber: 17 },
  { block: "I", floor: 3, roomNumber: 18 },
  { block: "I", floor: 3, roomNumber: 19 },
  { block: "I", floor: 3, roomNumber: 20 },
  { block: "I", floor: 4, roomNumber: 1 },
  { block: "I", floor: 4, roomNumber: 2 },
  { block: "I", floor: 4, roomNumber: 3 },
  { block: "I", floor: 4, roomNumber: 4 },
  { block: "I", floor: 4, roomNumber: 5 },
  { block: "I", floor: 4, roomNumber: 6 },
  { block: "I", floor: 4, roomNumber: 7 },
  { block: "I", floor: 4, roomNumber: 8 },
  { block: "I", floor: 4, roomNumber: 9 },
  { block: "I", floor: 4, roomNumber: 10 },
  { block: "I", floor: 4, roomNumber: 11 },
  { block: "I", floor: 4, roomNumber: 12 },
  { block: "I", floor: 4, roomNumber: 13 },
  { block: "I", floor: 4, roomNumber: 14 },
  { block: "I", floor: 4, roomNumber: 15 },
  { block: "I", floor: 4, roomNumber: 16 },
  { block: "I", floor: 4, roomNumber: 17 },
  { block: "I", floor: 4, roomNumber: 18 },
  { block: "I", floor: 4, roomNumber: 19 },
  { block: "I", floor: 4, roomNumber: 20 },
];

async function seedRooms() {
  const rooms = await Room.insertMany(rooms_seed);
  console.log(rooms);

  mongoose.connection.close();
  process.exit(0);
}

seedRooms();
